### ISSUE TITLE
Is it posible to incorporate Zstandard compression with IboxDB?

### ISSUE THREAD

**Issue by 99bits** [iboxdb/iboxdb.github.io#1]
Thank you Bruce for making this super awesome IboxDB project.

I'm researching IboxDB to use in Unity3d and considering also Sqlite.  I found that Sqlite supports Zstandard and the compression is phenomenal.  https://github.com/phiresky/sqlite-zstd

There is a Csharp version of Zstandard:  https://github.com/oleg-st/ZstdSharp

Do you think that it's possible to integrate Zstandard into IboxDB ?
Here is how Sqlite-zstd was done:  https://phiresky.github.io/blog/2022/sqlite-zstd/

**Comment by iboxdb** [comment]
these projects above are using unsafe methods,  iBoxDB uses safe code 100%.

```cs
namespace ZstdSharp
{
    public static unsafe class UnsafeHelper
    {
        public static void* PoisonMemory(void* destination, ulong size)
        {
            memset(destination, 0xCC, (uint) size);
            return destination;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void* malloc(uint size)
        {
#if DEBUG
            return PoisonMemory((void*)Marshal.AllocHGlobal((int)size), size);
#else
            return (void*) Marshal.AllocHGlobal((int) size);
#endif
        }
}
```
